"""Render the Ka-band CP feed-horn History (VBA) + bridge job. No CST access here.

Stepped circular horn (staircase surrogate of a conical horn; Cone syntax is not
verified on this install). Single-mode circular waveguide (TE11 cutoff ~20 GHz)
with four radial probes excited 0/-90/-180/-270 deg -> RHCP TE11 (m=+1 sequence
cannot excite TM01/TE21). Back short at lambda_g/4. All dimensions confidence C.
"""
import argparse,json,math
from pathlib import Path
import cst_com
from cst_geometry import cylinder,segment,port

ROOT=Path(__file__).resolve().parent
MONITORS=[25.5,26.25,27.0];SOLVE=(25.0,27.5)
DEFAULT={'wg_radius':4.4,'wall':1.0,'wg_length':20.0,'probe_z':4.4,'probe_radius':0.3,'probe_length':2.2,
         'feed_gap':0.3,'aperture_radius':7.9,'flare_length':20.0,'flare_steps':5}

class Recorder:
    def __init__(self):self.blocks=[]
    def _FlagAsMethod(self,name):pass
    def AddToHistory(self,name,code):self.blocks.append((name,code));return True

def horn(p,v):
    a=v['wg_radius'];t=v['wall']
    cylinder(p,'back_short',a+t,-t,0)
    cylinder(p,'waveguide',a+t,0,v['wg_length'],a)
    n=int(v['flare_steps']);dz=v['flare_length']/n if n else 0
    for i in range(n):
        r=a+(v['aperture_radius']-a)*(i+1)/n
        z0=v['wg_length']+i*dz
        # each step's inner radius r; outer r+t overlaps the previous wall -> closed step face
        cylinder(p,f'flare{i+1}',r+t,z0,z0+dz,r)
    z=v['probe_z'];g=v['feed_gap']
    for i in range(4):
        ang=i*math.pi/2;c,s=math.cos(ang),math.sin(ang)
        wall=(a*c,a*s,z);start=((a-g)*c,(a-g)*s,z);tip=((a-g-v['probe_length'])*c,(a-g-v['probe_length'])*s,z)
        segment(p,f'probe{i+1}',start,tip,v['probe_radius'])
        port(p,i+1,wall,start)
    return {'aperture_diameter':2*v['aperture_radius'],'total_length':v['wg_length']+v['flare_length']+t,
            'te11_cutoff_ghz':1.8412*299.792458/(2*math.pi*a),'tm01_cutoff_ghz':2.4048*299.792458/(2*math.pi*a)}

def render(label,v):
    out=ROOT/'tools'/'commands'/label
    if (ROOT/'projects'/f'{label}.cst').exists() or out.exists():raise FileExistsError(label)
    rec=Recorder();derived=horn(rec,v)
    for f in MONITORS:cst_com.monitor(rec,f)
    out.mkdir(parents=True)
    text=f"' {label}: generated by cst/generate_ka_feed.py (specs/kaband_dls.yaml)\n"
    for name,code in rec.blocks:text+=f"'@@ {name}\n{code.rstrip()}\n"
    (out/'history.vba').write_text(text,encoding='utf-8')
    steps=[{'action':'NewProject'},
           {'action':'History','file':'../../templates/units_solver_frequency.vba'},
           {'action':'History','file':'../../templates/boundaries_open.vba'},
           {'action':'History','file':'history.vba'},
           {'action':'History','file':'../../templates/mesh_resource_hex.vba'},
           {'action':'History','file':'../../templates/view_structure.vba'},
           {'action':'SaveAs','path':f'../../../projects/{label}.cst'},
           {'action':'Solve'},{'action':'Save'},
           {'action':'ExportSParameters','out':f'../../../results/{label}/s_parameters.csv','ports':4}]
    (out/'job.json').write_text(json.dumps({'label':label,'vars':{'fmin':str(SOLVE[0]),'fmax':str(SOLVE[1]),
        'accuracy':'-40','steps':'8','ratio':'5'},'steps':steps},indent=2),encoding='utf-8')
    (out/'candidate.json').write_text(json.dumps({'label':label,'inputs':v,'derived_mm_ghz':derived,
        'monitors_ghz':MONITORS,'phases_deg':[0,-90,-180,-270],'mesh':'Hex 8 cells/wavelength resource budget',
        'mesh_validation':'DISABLED_BY_USER'},indent=2),encoding='utf-8')
    return out,derived

if __name__=='__main__':
    a=argparse.ArgumentParser();a.add_argument('label');a.add_argument('--set',action='append',default=[])
    args=a.parse_args();v=dict(DEFAULT)
    for item in args.set:
        k,val=item.split('=',1)
        if k not in v:raise ValueError(k)
        v[k]=float(val)
    print(render(args.label,v))


