' SAR_LEAF_A_PATCH: generated by cst/generate_sar_leaf.py (specs/xband_sar.yaml)
'@@ ground
WCS.ActivateWCS "global"
With Brick
 .Reset
 .Name "ground"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .Xrange "-14.053", "14.053"
 .Yrange "-14.053", "14.053"
 .Zrange "-1.0", "0"
 .Create
End With
'@@ patch
WCS.ActivateWCS "global"
With Brick
 .Reset
 .Name "patch"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .Xrange "-7.75", "7.75"
 .Yrange "-8.5", "8.5"
 .Zrange "2.5", "3.0"
 .Create
End With
'@@ probe
With Cylinder
 .Reset
 .Name "probe"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.5"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0.5", "2.75"
 .Xcenter "2.5"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ Port 1
With DiscretePort
 .Reset
 .PortNumber "1"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "2.5", "0", "0"
 .Point2 "2.5", "0", "0.5"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ Farfield 7.85 GHz
With Monitor
 .Reset
 .Name "farfield (f=7.85)"
 .Domain "Frequency"
 .FieldType "Farfield"
 .Frequency "7.85"
 .Create
End With
'@@ Farfield 8 GHz
With Monitor
 .Reset
 .Name "farfield (f=8)"
 .Domain "Frequency"
 .FieldType "Farfield"
 .Frequency "8"
 .Create
End With
'@@ Farfield 8.15 GHz
With Monitor
 .Reset
 .Name "farfield (f=8.15)"
 .Domain "Frequency"
 .FieldType "Farfield"
 .Frequency "8.15"
 .Create
End With
