"""Render the X-band SAR leaf (single radiating element) History + bridge job."""
import argparse,json
from pathlib import Path
import yaml
import cst_com
from cst_com_common import brick_code,add_to_history
from cst_geometry import COMPONENT,cylinder,port

ROOT=Path(__file__).resolve().parent
SPEC=yaml.safe_load((ROOT/'specs/xband_sar.yaml').read_text(encoding='utf-8'))
MONITORS=[7.85,8.0,8.15];SOLVE=(7.6,8.4)

class Recorder:
    def __init__(self):self.blocks=[]
    def _FlagAsMethod(self,name):pass
    def AddToHistory(self,name,code):self.blocks.append((name,code));return True

def leaf(p,v):
    c=v['cell']/2;L=v['patch_length']/2;W=v['patch_width']/2;h=v['patch_height'];t=v['patch_thickness']
    add_to_history(p,'ground',brick_code('ground',COMPONENT,-c,c,-c,c,-v['ground_thickness'],0))
    add_to_history(p,'patch',brick_code('patch',COMPONENT,-L,L,-W,W,h,h+t))
    x=v['feed_offset'];g=v['feed_gap']
    xs=[x,-x] if v.get('dual_feed') else [x]   # dual: symmetric probes, excited 0/180 deg
    for i,xx in enumerate(xs):
        cylinder(p,f'probe{i+1}',v['probe_radius'],g,h+t/2,x=xx,y=0)
        port(p,i+1,(xx,0,0),(xx,0,g))
    return len(xs)

def render(label,v):
    out=ROOT/'tools'/'commands'/label
    if (ROOT/'projects'/f'{label}.cst').exists() or out.exists():raise FileExistsError(label)
    rec=Recorder();ports=leaf(rec,v)
    for f in MONITORS:cst_com.monitor(rec,f)
    out.mkdir(parents=True)
    text=f"' {label}: generated by cst/generate_sar_leaf.py (specs/xband_sar.yaml)\n"
    for name,code in rec.blocks:text+=f"'@@ {name}\n{code.rstrip()}\n"
    (out/'history.vba').write_text(text,encoding='utf-8')
    steps=[{'action':'NewProject'},
           {'action':'History','file':'../../templates/units_solver_frequency.vba'},
           {'action':'History','file':'../../templates/boundaries_open.vba'},
           {'action':'History','file':'history.vba'},
           {'action':'History','file':'../../templates/mesh_resource_hex.vba'},
           {'action':'History','file':'../../templates/view_structure.vba'},
           {'action':'SaveAs','path':f'../../../projects/{label}.cst'},
           {'action':'Solve'},{'action':'Save'},
           {'action':'ExportSParameters','out':f'../../../results/{label}/s_parameters.csv','ports':ports}]
    (out/'job.json').write_text(json.dumps({'label':label,'vars':{'fmin':str(SOLVE[0]),'fmax':str(SOLVE[1]),
        'accuracy':'-40','steps':'10','ratio':'5'},'steps':steps},indent=2),encoding='utf-8')
    (out/'candidate.json').write_text(json.dumps({'label':label,'inputs':v,'ports':ports,'phases_deg':[0,180][:ports],'monitors_ghz':MONITORS,
        'mesh':'Hex 10 cells/wavelength resource budget','mesh_validation':'DISABLED_BY_USER'},indent=2),encoding='utf-8')
    return out

if __name__=='__main__':
    a=argparse.ArgumentParser();a.add_argument('label');a.add_argument('--set',action='append',default=[])
    args=a.parse_args();v=dict(SPEC['leaf'])
    for item in args.set:
        k,val=item.split('=',1)
        if k not in v:raise ValueError(k)
        v[k]=float(val)
    print(render(args.label,v))
