function ok = run_all_tests()
%RUN_ALL_TESTS Portable (MATLAB+Octave) deterministic test runner for rfscreen.
%   Returns true if all tests passed. Does NOT call exit(); a CLI wrapper may.
    thisDir = fileparts(mfilename('fullpath'));
    repoRoot = fileparts(thisDir);
    addpath(fullfile(repoRoot, 'src'));
    addpath(thisDir);

    tests = { ...
        @test_coordinate, ...
        @test_geometry, ...
        @test_pattern, ...
        @test_pairwise, ...
        @test_multisystem, ...
        @test_invalid_inputs, ...
        @test_invariants, ...
        @test_architecture_boundary, ...
        @test_pattern_import, ...
        @test_pattern_duplicates, ...
        @test_pattern_periodic, ...
        @test_pattern_frame, ...
        @test_pattern_validation, ...
        @test_pattern_integration, ...
        @test_pattern_architecture, ...
        @test_spectrum, ...
        @test_filter, ...
        @test_spectral_coupling, ...
        @test_noise, ...
        @test_in_margin, ...
        @test_susceptibility_validity, ...
        @test_rf_coexistence_integration, ...
        @test_phase3_architecture, ...
        @test_compression, ...
        @test_blocking, ...
        @test_im3, ...
        @test_nonlinear_validity, ...
        @test_nonlinear_scenario, ...
        @test_phase4_architecture, ...
        @test_ray_intersection, ...
        @test_structure_fov, ...
        @test_los_blockage, ...
        @test_installed_pattern, ...
        @test_installed_environment_integration, ...
        @test_phase5_architecture, ...
        @test_phase6_audits };

    h = testutil.Harness();
    fprintf('Running %d test files...\n', numel(tests));
    for i = 1:numel(tests)
        fn = tests{i};
        name = func2str(fn);
        try
            fn(h);
            fprintf('  ran %s\n', name);
        catch err
            h.fail(['<file:' name '>'], sprintf('hard error: %s (%s)', err.message, err.identifier));
            fprintf('  ERROR in %s: %s\n', name, err.message);
        end
    end

    ok = h.report();
end
