' ISL_B3_FLAT_RG9P5: generated by cst/generate_isl.py from specs/xband_isl.yaml
' Verified History syntax only (cst_geometry / cst_com functions used for S/L-band runs).
'@@ Parameter ground_radius
StoreParameterWithDescription "ground_radius", "9.5", "documentation only; geometry is numeric"
'@@ Parameter floor_thickness
StoreParameterWithDescription "floor_thickness", "1", "documentation only; geometry is numeric"
'@@ Parameter rim_height
StoreParameterWithDescription "rim_height", "0", "documentation only; geometry is numeric"
'@@ Parameter rim_thickness
StoreParameterWithDescription "rim_thickness", "1", "documentation only; geometry is numeric"
'@@ Parameter patch_diameter
StoreParameterWithDescription "patch_diameter", "16.6", "documentation only; geometry is numeric"
'@@ Parameter patch_height
StoreParameterWithDescription "patch_height", "2.5", "documentation only; geometry is numeric"
'@@ Parameter patch_thickness
StoreParameterWithDescription "patch_thickness", "0.5", "documentation only; geometry is numeric"
'@@ Parameter feed_radius
StoreParameterWithDescription "feed_radius", "3", "documentation only; geometry is numeric"
'@@ Parameter probe_radius
StoreParameterWithDescription "probe_radius", "0.4", "documentation only; geometry is numeric"
'@@ Parameter feed_gap
StoreParameterWithDescription "feed_gap", "0.5", "documentation only; geometry is numeric"
'@@ ground_floor
With Cylinder
 .Reset
 .Name "ground_floor"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "9.5"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "-1", "0"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ patch
With Cylinder
 .Reset
 .Name "patch"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "8.3"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "2.5", "3"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ probe1
With Cylinder
 .Reset
 .Name "probe1"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.4"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0.5", "2.75"
 .Xcenter "3"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ Port 1
With DiscretePort
 .Reset
 .PortNumber "1"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "3", "0", "0"
 .Point2 "3", "0", "0.5"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ probe2
With Cylinder
 .Reset
 .Name "probe2"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.4"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0.5", "2.75"
 .Xcenter "1.83697019872e-16"
 .Ycenter "3"
 .Segments "0"
 .Create
End With
'@@ Port 2
With DiscretePort
 .Reset
 .PortNumber "2"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "1.83697019872e-16", "3", "0"
 .Point2 "1.83697019872e-16", "3", "0.5"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ probe3
With Cylinder
 .Reset
 .Name "probe3"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.4"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0.5", "2.75"
 .Xcenter "-3"
 .Ycenter "3.67394039744e-16"
 .Segments "0"
 .Create
End With
'@@ Port 3
With DiscretePort
 .Reset
 .PortNumber "3"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "-3", "3.67394039744e-16", "0"
 .Point2 "-3", "3.67394039744e-16", "0.5"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ probe4
With Cylinder
 .Reset
 .Name "probe4"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.4"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0.5", "2.75"
 .Xcenter "-5.51091059616e-16"
 .Ycenter "-3"
 .Segments "0"
 .Create
End With
'@@ Port 4
With DiscretePort
 .Reset
 .PortNumber "4"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "-5.51091059616e-16", "-3", "0"
 .Point2 "-5.51091059616e-16", "-3", "0.5"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ Farfield 8 GHz
With Monitor
 .Reset
 .Name "farfield (f=8)"
 .Domain "Frequency"
 .FieldType "Farfield"
 .Frequency "8"
 .Create
End With
'@@ Farfield 8.2 GHz
With Monitor
 .Reset
 .Name "farfield (f=8.2)"
 .Domain "Frequency"
 .FieldType "Farfield"
 .Frequency "8.2"
 .Create
End With
'@@ Farfield 8.4 GHz
With Monitor
 .Reset
 .Name "farfield (f=8.4)"
 .Domain "Frequency"
 .FieldType "Farfield"
 .Frequency "8.4"
 .Create
End With
