"""Render X-band ISL candidate History (VBA) + bridge job; no CST access here.

The geometry code is produced by the same verified functions used for the
accepted S-band/L-band models (cst_geometry, cst_com.monitor), captured by a
recorder instead of a live project. tools/invoke-cst.ps1 then executes the job
through PowerShell -> COM -> AddToHistory in a NEW project.
"""
import argparse,json,math
from pathlib import Path
import yaml
import cst_com
from cst_geometry import cylinder,segment,port,swept_wire

ROOT=Path(__file__).resolve().parent
SPEC=yaml.safe_load((ROOT/'specs/xband_isl.yaml').read_text(encoding='utf-8'))
F=SPEC['assumptions'][0]['value']
MONITORS=[F['fmin_ghz'],F['f0_ghz'],F['fmax_ghz']]
SOLVE=(round(F['fmin_ghz']-0.1,3),round(F['fmax_ghz']+0.1,3))

class Recorder:
    """Duck-typed stand-in for the CST project: records AddToHistory blocks."""
    def __init__(self):self.blocks=[]
    def _FlagAsMethod(self,name):pass
    def AddToHistory(self,name,code):self.blocks.append((name,code));return True

def helix_scaled(p,v):
    """Accepted S-band 4-arm resonant multifilar, scaled and mirrored (RHCP)."""
    s=v['scale'];r=9*s;h=52*s;n=0.5;gap=1.2*s;w=1.5*s;base=32*s;g=20*s
    cylinder(p,'base_floor',32.5*s,-base,-g)
    for name,ri,ro in [('base_center',0,12),('groove_wall_1',20,22),('outer_wall',30,32.5)]:
        cylinder(p,name,ro*s,-g,0,ri*s)
    count=round(n*24);top=gap+4*w+h
    for arm in range(4):
        phase=math.pi*arm/2;x,y=r*math.cos(phase),r*math.sin(phase);name=f'arm{arm+1}'
        pts=[(x,y,gap),(x,y,gap+2*w)]
        for i in range(count+1):
            t=i/count;angle=phase-2*math.pi*n*t   # mirrored winding
            pts.append((r*math.cos(angle),r*math.sin(angle),gap+4*w+h*t))
        swept_wire(p,name,pts,w)
        end=phase-2*math.pi*n
        segment(p,f'{name}_termination',(r*math.cos(end),r*math.sin(end),top),(0,0,top),w)
        port(p,arm+1,(x,y,0),(x,y,gap))
    return {'helix_diameter':2*r,'helix_height':h,'turns':n,'wire_radius':w,'feed_gap':gap,
            'base_diameter':65*s,'base_depth':base,'groove_depth':g,'winding':'mirrored (clockwise rising)'}

def cup_patch(p,v):
    rg=v['ground_radius'];rim=v['rim_height'];t=v['rim_thickness']
    cylinder(p,'ground_floor',rg,-v['floor_thickness'],0)
    if rim>0:cylinder(p,'rim',rg,0,rim,rg-t)
    h=v['patch_height'];th=v['patch_thickness']
    cylinder(p,'patch',v['patch_diameter']/2,h,h+th)
    gap=v['feed_gap']
    for i in range(4):
        a=i*math.pi/2;x=v['feed_radius']*math.cos(a);y=v['feed_radius']*math.sin(a)
        cylinder(p,f'probe{i+1}',v['probe_radius'],gap,h+th/2,x=x,y=y)
        port(p,i+1,(x,y,0),(x,y,gap))
    return dict(v)

def render(label,topology,values,mesh_resource):
    out=ROOT/'tools'/'commands'/label
    project=ROOT/'projects'/f'{label}.cst'
    if project.exists() or out.exists():raise FileExistsError(f'Refusing overwrite: {label}')
    rec=Recorder()
    for k,val in values.items():
        if isinstance(val,(int,float)):
            rec.AddToHistory(f'Parameter {k}',f'StoreParameterWithDescription "{k}", "{val:.12g}", "documentation only; geometry is numeric"')
    builder={'helix':helix_scaled,'cuppatch':cup_patch}[topology]
    derived=builder(rec,values)
    for f in MONITORS:cst_com.monitor(rec,f)
    out.mkdir(parents=True)
    text=f"' {label}: generated by cst/generate_isl.py from specs/xband_isl.yaml\n"
    text+="' Verified History syntax only (cst_geometry / cst_com functions used for S/L-band runs).\n"
    for name,code in rec.blocks:text+=f"'@@ {name}\n{code.rstrip()}\n"
    (out/'history.vba').write_text(text,encoding='utf-8')
    steps=[{'action':'NewProject'},
           {'action':'History','file':'../../templates/units_solver_frequency.vba'},
           {'action':'History','file':'../../templates/boundaries_open.vba'},
           {'action':'History','file':'history.vba'}]
    if mesh_resource:steps.append({'action':'History','file':'../../templates/mesh_resource_hex.vba'})
    steps+=[{'action':'History','file':'../../templates/view_structure.vba'},
            {'action':'SaveAs','path':f'../../../projects/{label}.cst'},
            {'action':'Solve'},{'action':'Save'},
            {'action':'ExportSParameters','out':f'../../../results/{label}/s_parameters.csv','ports':4}]
    job={'label':label,'topology':topology,'vars':{'fmin':str(SOLVE[0]),'fmax':str(SOLVE[1]),'accuracy':'-40',
         'steps':'8','ratio':'5'},'steps':steps}
    (out/'job.json').write_text(json.dumps(job,indent=2),encoding='utf-8')
    (out/'candidate.json').write_text(json.dumps({'label':label,'topology':topology,'inputs':values,
        'derived_geometry_mm':derived,'monitors_ghz':MONITORS,'solve_range_ghz':SOLVE,
        'phases_deg':[0,-90,-180,-270],'mesh':'Hex 8 cells/wavelength resource budget' if mesh_resource else 'CST default (as S-band)',
        'mesh_validation':'DISABLED_BY_USER','assumptions':[a['id'] for a in SPEC['assumptions']]},indent=2),encoding='utf-8')
    return out

if __name__=='__main__':
    a=argparse.ArgumentParser();a.add_argument('label');a.add_argument('--base',required=True,
        help='candidate key in specs/xband_isl.yaml')
    a.add_argument('--set',action='append',default=[],metavar='PARAM=VALUE')
    args=a.parse_args();c=SPEC['candidates'][args.base]
    if 'scale' in c:values={'scale':c['scale']};topology='helix';mesh=False
    else:values=dict(c['dimensions_mm']);topology='cuppatch';mesh=True
    for item in args.set:
        k,val=item.split('=',1)
        if k not in values:raise ValueError(f'Unknown parameter {k}')
        values[k]=float(val)
    print(render(args.label,topology,values,mesh))
