' ISL_FIXED_10G6: generated by cst/generate_isl.py from specs/xband_isl.yaml
' Verified History syntax only (cst_geometry / cst_com functions used for S/L-band runs).
'@@ Parameter ground_radius
StoreParameterWithDescription "ground_radius", "14.7", "documentation only; geometry is numeric"
'@@ Parameter floor_thickness
StoreParameterWithDescription "floor_thickness", "0.789", "documentation only; geometry is numeric"
'@@ Parameter rim_height
StoreParameterWithDescription "rim_height", "3.154", "documentation only; geometry is numeric"
'@@ Parameter rim_thickness
StoreParameterWithDescription "rim_thickness", "0.789", "documentation only; geometry is numeric"
'@@ Parameter patch_diameter
StoreParameterWithDescription "patch_diameter", "13.089", "documentation only; geometry is numeric"
'@@ Parameter patch_height
StoreParameterWithDescription "patch_height", "1.971", "documentation only; geometry is numeric"
'@@ Parameter patch_thickness
StoreParameterWithDescription "patch_thickness", "0.394", "documentation only; geometry is numeric"
'@@ Parameter feed_radius
StoreParameterWithDescription "feed_radius", "2.365", "documentation only; geometry is numeric"
'@@ Parameter probe_radius
StoreParameterWithDescription "probe_radius", "0.315", "documentation only; geometry is numeric"
'@@ Parameter feed_gap
StoreParameterWithDescription "feed_gap", "0.394", "documentation only; geometry is numeric"
'@@ ground_floor
With Cylinder
 .Reset
 .Name "ground_floor"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "14.7"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "-0.789", "0"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ rim
With Cylinder
 .Reset
 .Name "rim"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "14.7"
 .InnerRadius "13.911"
 .Axis "z"
 .Zrange "0", "3.154"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ patch
With Cylinder
 .Reset
 .Name "patch"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "6.5445"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "1.971", "2.365"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ probe1
With Cylinder
 .Reset
 .Name "probe1"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.315"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0.394", "2.168"
 .Xcenter "2.365"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ Port 1
With DiscretePort
 .Reset
 .PortNumber "1"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "2.365", "0", "0"
 .Point2 "2.365", "0", "0.394"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ probe2
With Cylinder
 .Reset
 .Name "probe2"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.315"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0.394", "2.168"
 .Xcenter "1.44814483999e-16"
 .Ycenter "2.365"
 .Segments "0"
 .Create
End With
'@@ Port 2
With DiscretePort
 .Reset
 .PortNumber "2"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "1.44814483999e-16", "2.365", "0"
 .Point2 "1.44814483999e-16", "2.365", "0.394"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ probe3
With Cylinder
 .Reset
 .Name "probe3"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.315"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0.394", "2.168"
 .Xcenter "-2.365"
 .Ycenter "2.89628967998e-16"
 .Segments "0"
 .Create
End With
'@@ Port 3
With DiscretePort
 .Reset
 .PortNumber "3"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "-2.365", "2.89628967998e-16", "0"
 .Point2 "-2.365", "2.89628967998e-16", "0.394"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ probe4
With Cylinder
 .Reset
 .Name "probe4"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.315"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0.394", "2.168"
 .Xcenter "-4.34443451998e-16"
 .Ycenter "-2.365"
 .Segments "0"
 .Create
End With
'@@ Port 4
With DiscretePort
 .Reset
 .PortNumber "4"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "-4.34443451998e-16", "-2.365", "0"
 .Point2 "-4.34443451998e-16", "-2.365", "0.394"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ Farfield 10.4 GHz
With Monitor
 .Reset
 .Name "farfield (f=10.4)"
 .Domain "Frequency"
 .FieldType "Farfield"
 .Frequency "10.4"
 .Create
End With
'@@ Farfield 10.55 GHz
With Monitor
 .Reset
 .Name "farfield (f=10.55)"
 .Domain "Frequency"
 .FieldType "Farfield"
 .Frequency "10.55"
 .Create
End With
'@@ Farfield 10.6 GHz
With Monitor
 .Reset
 .Name "farfield (f=10.6)"
 .Domain "Frequency"
 .FieldType "Farfield"
 .Frequency "10.6"
 .Create
End With
'@@ Farfield 10.65 GHz
With Monitor
 .Reset
 .Name "farfield (f=10.65)"
 .Domain "Frequency"
 .FieldType "Farfield"
 .Frequency "10.65"
 .Create
End With
