' KA_FEED_A_STEPHORN: generated by cst/generate_ka_feed.py (specs/kaband_dls.yaml)
'@@ back_short
With Cylinder
 .Reset
 .Name "back_short"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "5.4"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "-1", "0"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ waveguide
With Cylinder
 .Reset
 .Name "waveguide"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "5.4"
 .InnerRadius "4.4"
 .Axis "z"
 .Zrange "0", "20"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ flare1
With Cylinder
 .Reset
 .Name "flare1"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "6.1"
 .InnerRadius "5.1"
 .Axis "z"
 .Zrange "20", "24"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ flare2
With Cylinder
 .Reset
 .Name "flare2"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "6.8"
 .InnerRadius "5.8"
 .Axis "z"
 .Zrange "24", "28"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ flare3
With Cylinder
 .Reset
 .Name "flare3"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "7.5"
 .InnerRadius "6.5"
 .Axis "z"
 .Zrange "28", "32"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ flare4
With Cylinder
 .Reset
 .Name "flare4"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "8.2"
 .InnerRadius "7.2"
 .Axis "z"
 .Zrange "32", "36"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ flare5
With Cylinder
 .Reset
 .Name "flare5"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "8.9"
 .InnerRadius "7.9"
 .Axis "z"
 .Zrange "36", "40"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ probe1
With Cylinder
 .Reset
 .Name "probe1"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.3"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0", "2.2"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:probe1"
 .Origin "Free"
 .Center "0", "0", "0"
 .Angle "0", "90", "0"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .RotateAdvanced
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:probe1"
 .Origin "Free"
 .Center "0", "0", "0"
 .Angle "0", "0", "180"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .RotateAdvanced
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:probe1"
 .Vector "4.1", "0", "4.4"
 .UsePickedPoints "False"
 .InvertPickedPoints "False"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .TranslateAdvanced
End With
'@@ Port 1
With DiscretePort
 .Reset
 .PortNumber "1"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "4.4", "0", "4.4"
 .Point2 "4.1", "0", "4.4"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ probe2
With Cylinder
 .Reset
 .Name "probe2"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.3"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0", "2.2"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:probe2"
 .Origin "Free"
 .Center "0", "0", "0"
 .Angle "0", "90", "0"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .RotateAdvanced
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:probe2"
 .Origin "Free"
 .Center "0", "0", "0"
 .Angle "0", "0", "-90"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .RotateAdvanced
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:probe2"
 .Vector "2.51052593825e-16", "4.1", "4.4"
 .UsePickedPoints "False"
 .InvertPickedPoints "False"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .TranslateAdvanced
End With
'@@ Port 2
With DiscretePort
 .Reset
 .PortNumber "2"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "2.69422295812e-16", "4.4", "4.4"
 .Point2 "2.51052593825e-16", "4.1", "4.4"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ probe3
With Cylinder
 .Reset
 .Name "probe3"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.3"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0", "2.2"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:probe3"
 .Origin "Free"
 .Center "0", "0", "0"
 .Angle "0", "90", "0"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .RotateAdvanced
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:probe3"
 .Origin "Free"
 .Center "0", "0", "0"
 .Angle "0", "0", "-7.01670929853e-15"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .RotateAdvanced
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:probe3"
 .Vector "-4.1", "5.0210518765e-16", "4.4"
 .UsePickedPoints "False"
 .InvertPickedPoints "False"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .TranslateAdvanced
End With
'@@ Port 3
With DiscretePort
 .Reset
 .PortNumber "3"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "-4.4", "5.38844591625e-16", "4.4"
 .Point2 "-4.1", "5.0210518765e-16", "4.4"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ probe4
With Cylinder
 .Reset
 .Name "probe4"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.3"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0", "2.2"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:probe4"
 .Origin "Free"
 .Center "0", "0", "0"
 .Angle "0", "90", "0"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .RotateAdvanced
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:probe4"
 .Origin "Free"
 .Center "0", "0", "0"
 .Angle "0", "0", "90"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .RotateAdvanced
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:probe4"
 .Vector "-7.53157781476e-16", "-4.1", "4.4"
 .UsePickedPoints "False"
 .InvertPickedPoints "False"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .TranslateAdvanced
End With
'@@ Port 4
With DiscretePort
 .Reset
 .PortNumber "4"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "-8.08266887437e-16", "-4.4", "4.4"
 .Point2 "-7.53157781476e-16", "-4.1", "4.4"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ Farfield 25.5 GHz
With Monitor
 .Reset
 .Name "farfield (f=25.5)"
 .Domain "Frequency"
 .FieldType "Farfield"
 .Frequency "25.5"
 .Create
End With
'@@ Farfield 26.25 GHz
With Monitor
 .Reset
 .Name "farfield (f=26.25)"
 .Domain "Frequency"
 .FieldType "Farfield"
 .Frequency "26.25"
 .Create
End With
'@@ Farfield 27 GHz
With Monitor
 .Reset
 .Name "farfield (f=27)"
 .Domain "Frequency"
 .FieldType "Farfield"
 .Frequency "27"
 .Create
End With
