' ISL_A_QHELIX_SCALED: generated by cst/generate_isl.py from specs/xband_isl.yaml
' Verified History syntax only (cst_geometry / cst_com functions used for S/L-band runs).
'@@ Parameter scale
StoreParameterWithDescription "scale", "0.274390244", "documentation only; geometry is numeric"
'@@ base_floor
With Cylinder
 .Reset
 .Name "base_floor"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "8.91768293"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "-8.780487808", "-5.48780488"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ base_center
With Cylinder
 .Reset
 .Name "base_center"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "3.292682928"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "-5.48780488", "0"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ groove_wall_1
With Cylinder
 .Reset
 .Name "groove_wall_1"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "6.036585368"
 .InnerRadius "5.48780488"
 .Axis "z"
 .Zrange "-5.48780488", "0"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ outer_wall
With Cylinder
 .Reset
 .Name "outer_wall"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "8.91768293"
 .InnerRadius "8.23170732"
 .Axis "z"
 .Zrange "-5.48780488", "0"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
'@@ arm1
Curve.NewCurve "path_arm1"
With Polygon3D
 .Reset
 .Name "centerline"
 .Curve "path_arm1"
 .SetInterpolation "Spline"
 .Point "2.469512196", "0", "0.3292682928"
 .Point "2.469512196", "0", "1.1524390248"
 .Point "2.469512196", "0", "1.9756097568"
 .Point "2.38536560845", "-0.639156788438", "3.16463414747"
 .Point "2.13866029669", "-1.234756098", "4.35365853813"
 .Point "1.74620882001", "-1.74620882001", "5.5426829288"
 .Point "1.234756098", "-2.13866029669", "6.73170731947"
 .Point "0.639156788438", "-2.38536560845", "7.92073171013"
 .Point "1.51214010314e-16", "-2.469512196", "9.1097561008"
 .Point "-0.639156788438", "-2.38536560845", "10.2987804915"
 .Point "-1.234756098", "-2.13866029669", "11.4878048821"
 .Point "-1.74620882001", "-1.74620882001", "12.6768292728"
 .Point "-2.13866029669", "-1.234756098", "13.8658536635"
 .Point "-2.38536560845", "-0.639156788438", "15.0548780541"
 .Point "-2.469512196", "-3.02428020629e-16", "16.2439024448"
 .Create
End With
With Circle
 .Reset
 .Name "profile"
 .Curve "path_arm1"
 .Radius "0.411585366"
 .Xcenter "2.469512196"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
With Transform
 .Reset
 .Name "path_arm1:profile"
 .Vector "0", "0", "0.3292682928"
 .UsePickedPoints "False"
 .InvertPickedPoints "False"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .TranslateCurve
End With
With SweepCurve
 .Reset
 .Name "arm1"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .Twistangle "0"
 .Taperangle "0"
 .ProjectProfileToPathAdvanced "True"
 .Path "path_arm1:centerline"
 .Curve "path_arm1:profile"
 .Create
End With
'@@ arm1_termination
With Cylinder
 .Reset
 .Name "arm1_termination"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.411585366"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0", "2.469512196"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:arm1_termination"
 .Origin "Free"
 .Center "0", "0", "0"
 .Angle "0", "90", "0"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .RotateAdvanced
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:arm1_termination"
 .Origin "Free"
 .Center "0", "0", "0"
 .Angle "0", "0", "7.01670929853e-15"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .RotateAdvanced
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:arm1_termination"
 .Vector "-2.469512196", "-3.02428020629e-16", "16.2439024448"
 .UsePickedPoints "False"
 .InvertPickedPoints "False"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .TranslateAdvanced
End With
'@@ Port 1
With DiscretePort
 .Reset
 .PortNumber "1"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "2.469512196", "0", "0"
 .Point2 "2.469512196", "0", "0.3292682928"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ arm2
Curve.NewCurve "path_arm2"
With Polygon3D
 .Reset
 .Name "centerline"
 .Curve "path_arm2"
 .SetInterpolation "Spline"
 .Point "1.51214010314e-16", "2.469512196", "0.3292682928"
 .Point "1.51214010314e-16", "2.469512196", "1.1524390248"
 .Point "1.51214010314e-16", "2.469512196", "1.9756097568"
 .Point "0.639156788438", "2.38536560845", "3.16463414747"
 .Point "1.234756098", "2.13866029669", "4.35365853813"
 .Point "1.74620882001", "1.74620882001", "5.5426829288"
 .Point "2.13866029669", "1.234756098", "6.73170731947"
 .Point "2.38536560845", "0.639156788438", "7.92073171013"
 .Point "2.469512196", "0", "9.1097561008"
 .Point "2.38536560845", "-0.639156788438", "10.2987804915"
 .Point "2.13866029669", "-1.234756098", "11.4878048821"
 .Point "1.74620882001", "-1.74620882001", "12.6768292728"
 .Point "1.234756098", "-2.13866029669", "13.8658536635"
 .Point "0.639156788438", "-2.38536560845", "15.0548780541"
 .Point "1.51214010314e-16", "-2.469512196", "16.2439024448"
 .Create
End With
With Circle
 .Reset
 .Name "profile"
 .Curve "path_arm2"
 .Radius "0.411585366"
 .Xcenter "1.51214010314e-16"
 .Ycenter "2.469512196"
 .Segments "0"
 .Create
End With
With Transform
 .Reset
 .Name "path_arm2:profile"
 .Vector "0", "0", "0.3292682928"
 .UsePickedPoints "False"
 .InvertPickedPoints "False"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .TranslateCurve
End With
With SweepCurve
 .Reset
 .Name "arm2"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .Twistangle "0"
 .Taperangle "0"
 .ProjectProfileToPathAdvanced "True"
 .Path "path_arm2:centerline"
 .Curve "path_arm2:profile"
 .Create
End With
'@@ arm2_termination
With Cylinder
 .Reset
 .Name "arm2_termination"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.411585366"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0", "2.469512196"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:arm2_termination"
 .Origin "Free"
 .Center "0", "0", "0"
 .Angle "0", "90", "0"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .RotateAdvanced
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:arm2_termination"
 .Origin "Free"
 .Center "0", "0", "0"
 .Angle "0", "0", "90"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .RotateAdvanced
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:arm2_termination"
 .Vector "1.51214010314e-16", "-2.469512196", "16.2439024448"
 .UsePickedPoints "False"
 .InvertPickedPoints "False"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .TranslateAdvanced
End With
'@@ Port 2
With DiscretePort
 .Reset
 .PortNumber "2"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "1.51214010314e-16", "2.469512196", "0"
 .Point2 "1.51214010314e-16", "2.469512196", "0.3292682928"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ arm3
Curve.NewCurve "path_arm3"
With Polygon3D
 .Reset
 .Name "centerline"
 .Curve "path_arm3"
 .SetInterpolation "Spline"
 .Point "-2.469512196", "3.02428020629e-16", "0.3292682928"
 .Point "-2.469512196", "3.02428020629e-16", "1.1524390248"
 .Point "-2.469512196", "3.02428020629e-16", "1.9756097568"
 .Point "-2.38536560845", "0.639156788438", "3.16463414747"
 .Point "-2.13866029669", "1.234756098", "4.35365853813"
 .Point "-1.74620882001", "1.74620882001", "5.5426829288"
 .Point "-1.234756098", "2.13866029669", "6.73170731947"
 .Point "-0.639156788438", "2.38536560845", "7.92073171013"
 .Point "1.51214010314e-16", "2.469512196", "9.1097561008"
 .Point "0.639156788438", "2.38536560845", "10.2987804915"
 .Point "1.234756098", "2.13866029669", "11.4878048821"
 .Point "1.74620882001", "1.74620882001", "12.6768292728"
 .Point "2.13866029669", "1.234756098", "13.8658536635"
 .Point "2.38536560845", "0.639156788438", "15.0548780541"
 .Point "2.469512196", "0", "16.2439024448"
 .Create
End With
With Circle
 .Reset
 .Name "profile"
 .Curve "path_arm3"
 .Radius "0.411585366"
 .Xcenter "-2.469512196"
 .Ycenter "3.02428020629e-16"
 .Segments "0"
 .Create
End With
With Transform
 .Reset
 .Name "path_arm3:profile"
 .Vector "0", "0", "0.3292682928"
 .UsePickedPoints "False"
 .InvertPickedPoints "False"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .TranslateCurve
End With
With SweepCurve
 .Reset
 .Name "arm3"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .Twistangle "0"
 .Taperangle "0"
 .ProjectProfileToPathAdvanced "True"
 .Path "path_arm3:centerline"
 .Curve "path_arm3:profile"
 .Create
End With
'@@ arm3_termination
With Cylinder
 .Reset
 .Name "arm3_termination"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.411585366"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0", "2.469512196"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:arm3_termination"
 .Origin "Free"
 .Center "0", "0", "0"
 .Angle "0", "90", "0"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .RotateAdvanced
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:arm3_termination"
 .Origin "Free"
 .Center "0", "0", "0"
 .Angle "0", "0", "180"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .RotateAdvanced
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:arm3_termination"
 .Vector "2.469512196", "0", "16.2439024448"
 .UsePickedPoints "False"
 .InvertPickedPoints "False"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .TranslateAdvanced
End With
'@@ Port 3
With DiscretePort
 .Reset
 .PortNumber "3"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "-2.469512196", "3.02428020629e-16", "0"
 .Point2 "-2.469512196", "3.02428020629e-16", "0.3292682928"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ arm4
Curve.NewCurve "path_arm4"
With Polygon3D
 .Reset
 .Name "centerline"
 .Curve "path_arm4"
 .SetInterpolation "Spline"
 .Point "-4.53642030943e-16", "-2.469512196", "0.3292682928"
 .Point "-4.53642030943e-16", "-2.469512196", "1.1524390248"
 .Point "-4.53642030943e-16", "-2.469512196", "1.9756097568"
 .Point "-0.639156788438", "-2.38536560845", "3.16463414747"
 .Point "-1.234756098", "-2.13866029669", "4.35365853813"
 .Point "-1.74620882001", "-1.74620882001", "5.5426829288"
 .Point "-2.13866029669", "-1.234756098", "6.73170731947"
 .Point "-2.38536560845", "-0.639156788438", "7.92073171013"
 .Point "-2.469512196", "3.02428020629e-16", "9.1097561008"
 .Point "-2.38536560845", "0.639156788438", "10.2987804915"
 .Point "-2.13866029669", "1.234756098", "11.4878048821"
 .Point "-1.74620882001", "1.74620882001", "12.6768292728"
 .Point "-1.234756098", "2.13866029669", "13.8658536635"
 .Point "-0.639156788438", "2.38536560845", "15.0548780541"
 .Point "1.51214010314e-16", "2.469512196", "16.2439024448"
 .Create
End With
With Circle
 .Reset
 .Name "profile"
 .Curve "path_arm4"
 .Radius "0.411585366"
 .Xcenter "-4.53642030943e-16"
 .Ycenter "-2.469512196"
 .Segments "0"
 .Create
End With
With Transform
 .Reset
 .Name "path_arm4:profile"
 .Vector "0", "0", "0.3292682928"
 .UsePickedPoints "False"
 .InvertPickedPoints "False"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .TranslateCurve
End With
With SweepCurve
 .Reset
 .Name "arm4"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .Twistangle "0"
 .Taperangle "0"
 .ProjectProfileToPathAdvanced "True"
 .Path "path_arm4:centerline"
 .Curve "path_arm4:profile"
 .Create
End With
'@@ arm4_termination
With Cylinder
 .Reset
 .Name "arm4_termination"
 .Component "RECONSTRUCTION"
 .Material "PEC"
 .OuterRadius "0.411585366"
 .InnerRadius "0"
 .Axis "z"
 .Zrange "0", "2.469512196"
 .Xcenter "0"
 .Ycenter "0"
 .Segments "0"
 .Create
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:arm4_termination"
 .Origin "Free"
 .Center "0", "0", "0"
 .Angle "0", "90", "0"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .RotateAdvanced
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:arm4_termination"
 .Origin "Free"
 .Center "0", "0", "0"
 .Angle "0", "0", "-90"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .RotateAdvanced
End With
With Transform
 .Reset
 .Name "RECONSTRUCTION:arm4_termination"
 .Vector "1.51214010314e-16", "2.469512196", "16.2439024448"
 .UsePickedPoints "False"
 .InvertPickedPoints "False"
 .MultipleObjects "False"
 .GroupObjects "False"
 .Repetitions "1"
 .MultipleSelection "False"
 .TranslateAdvanced
End With
'@@ Port 4
With DiscretePort
 .Reset
 .PortNumber "4"
 .Type "SParameter"
 .Impedance "50"
 .Voltage "1"
 .Current "1"
 .Point1 "-4.53642030943e-16", "-2.469512196", "0"
 .Point2 "-4.53642030943e-16", "-2.469512196", "0.3292682928"
 .UsePickedPoints "False"
 .LocalCoordinates "False"
 .Monitor "False"
 .Create
End With
'@@ Farfield 8 GHz
With Monitor
 .Reset
 .Name "farfield (f=8)"
 .Domain "Frequency"
 .FieldType "Farfield"
 .Frequency "8"
 .Create
End With
'@@ Farfield 8.2 GHz
With Monitor
 .Reset
 .Name "farfield (f=8.2)"
 .Domain "Frequency"
 .FieldType "Farfield"
 .Frequency "8.2"
 .Create
End With
'@@ Farfield 8.4 GHz
With Monitor
 .Reset
 .Name "farfield (f=8.4)"
 .Domain "Frequency"
 .FieldType "Farfield"
 .Frequency "8.4"
 .Create
End With
